PC-904 Include Shell referrals in Octopus csv
UKGovernmentBEIS/help-to-heat-GBIS pull request #286
Opened 2024-03-18 11:27 UTC by samyou-softwire

closes [PC-904](https://beisdigital.atlassian.net/browse/PC-904)

though the ticket implies this is backend work, the actual substitution takes place on the frontend

follows the same format as the other converter logic, where on submission the 'supplier' value is changed

note the 'user_selected_supplier' field on the csv will always show the supplier selected, fulfilling the requirement to be able to differentiate pure octopus referrals

includes a new test to verify

2024-03-18 16:07 UTC, jdgage requested changes
One thing on the ticket that I want to check is that we have the requirement that Shell referrals should have "Shell" noted against them somewhere in the export CSV. Does that already happen automatically, or is it missing?

2024-03-18 16:07 UTC, jdgage commented on tests/test_frontdoor.py
> +def test_shell_to_octopus():
Not going to suggest we attack existing tests here, but at least when adding new ones I think we should try for good naming: can this be more descriptive of what it's actually testing? Something of the form "X should Y [when Z]"?

2024-03-19 09:24 UTC, samyou-softwire commented
> One thing on the ticket that I want to check is that we have the requirement that Shell referrals should have "Shell" noted against them somewhere in the export CSV. Does that already happen automatically, or is it missing?

@jdgage yes - the export csv always has a 'user selected supplier' field which is always what the user selects on the supplier select page

2024-03-19 14:49 UTC, jdgage approved these changes

2024-03-19 15:57 UTC, merged