PC-343: Add to confirm and submit checkbox text
UKGovernmentBEIS/help-to-heat-GBIS pull request #34
Opened 2023-07-12 14:03 UTC by chidin194

![image](https://github.com/UKGovernmentBEIS/help-to-heat-GBIS/assets/104014956/e02be97c-5bb2-4489-a110-76525d67c3c1)

2023-07-12 14:18 UTC, CheshireSwift requested changes
Couple of fixes required to the HTML. Haven't checked copy in detail.

2023-07-12 16:49 UTC, CheshireSwift commented on help_to_heat/templates/frontdoor/confirm-and-submit.html
> +                <p><a class="govuk-link" href="#">Further information on our GDPR UK Privacy Policy.</a></p>
Yeah, I suspect it's meant to be a link somewhere at some point, but where might not be decided yet.

2023-07-12 16:51 UTC, CheshireSwift commented on help_to_heat/templates/frontdoor/confirm-and-submit.html
> +                <span class="govuk-heading-s">What is the Energy Company Obligation?</span>
Per the design system:

> But change it if your pages feel unbalanced – the heading class you use does not always need to correspond to the heading level.

So I think it's okay to be whichever size we feel like. Given goals of:

* Matching the design.
* Having correct heading nesting.
* Matching the style to the tag.

I'm happy to break the third one in the interest of preserving the other two 🙂

2023-07-13 09:48 UTC, chidin194 commented on help_to_heat/templates/frontdoor/confirm-and-submit.html
> +                <p><a class="govuk-link" href="#">Further information on our GDPR UK Privacy Policy.</a></p>
Confirmed with Allison it should redirect to the Privacy Policy page, added href in

2023-07-13 09:48 UTC, chidin194 commented on help_to_heat/templates/frontdoor/confirm-and-submit.html
> +                <span class="govuk-heading-s">What is the Energy Company Obligation?</span>
Matched design, thanks for explaining :)

2023-07-13 10:32 UTC, CheshireSwift approved these changes

2023-07-13 11:49 UTC, merged