PC-1354: Validate entered postcodes on address search
UKGovernmentBEIS/help-to-heat-GBIS pull request #372
Opened 2024-10-16 10:50 UTC by Glenn-Clarke

[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1354)

# Description

Added HUG2 postcode validation to address entry. 
This prevents partial postcodes from being entered, narrowing the property search.

# Checklist

- [x] I have made any necessary updates to the documentation
- [x] I have checked there are no unnecessary IDE warnings in this PR
- [x] I have checked there are no unintentional line ending changes
- [x] I have added tests where applicable
- [x] If I have made any changes to the code, I have used the IDE auto-formatter on it
- [x] If I have made any changes to Python files (even if not changing any content strings), I have run `make extract-translations`
- [x] If I have made any changes to website flow, I have updated the [Flow Miro Board](https://miro.com/app/board/uXjVK4AgQ3E=/)
- [x] If I have made any changes to website flow, I have checked forward and back behaviour is still consistent

# Screenshots

![{F952A3CD-9FBB-4E80-B353-80E83108F753}](https://github.com/user-attachments/assets/aa53f181-57a2-44b1-99fd-e33e97bf98d1)

![{01FB09BA-ADCA-46D0-9DD2-20896935B557}](https://github.com/user-attachments/assets/404db9f0-553e-4530-9b4b-e2c635b1a411)

2024-10-16 15:13 UTC, jdgage requested changes

2024-10-16 15:13 UTC, jdgage commented on help_to_heat/frontdoor/schemas.py
> +                raise ValidationError([_("Enter a valid UK postcode")])
Could condense this and make it a little clearer by inverting the check:
```suggestion
            if not any(map(lambda pattern: re.match(pattern, value), postcode_regex_collection)):
                raise ValidationError([_("Enter a valid UK postcode")])
```

2024-10-16 16:06 UTC, jdgage commented on help_to_heat/frontdoor/schemas.py
> +                raise ValidationError([_("Enter a valid UK postcode")])
Yes was going to say there was probably a more Python way to write the same thing

2024-10-16 16:07 UTC, jdgage commented on help_to_heat/frontdoor/schemas.py
> +            for valid_pattern in postcode_regex_collection:
Agree + would drop "collection" as that's self evident

2024-10-17 08:24 UTC, Glenn-Clarke commented on help_to_heat/frontdoor/schemas.py
> +            value = value.upper().replace(" ", "")
It doesn't appear to, no. 
Is there a situation where a user could get that character in there? (I guess if they copy/paste?)

2024-10-17 09:23 UTC, Glenn-Clarke commented on help_to_heat/frontdoor/schemas.py
> +            value = value.upper().replace(" ", "")
I've changed how the replacement is done, so it picks up other whitespace characters like tabs. I've also moved the upper after the replacement for a (negligible) efficiency saving.

2024-10-17 15:47 UTC, jdgage commented on help_to_heat/frontdoor/schemas.py
> +            standardised_value = re.sub(r'\s', '', value).upper()
👍

2024-10-17 15:48 UTC, jdgage approved these changes

2024-10-17 15:48 UTC, merged