PC-441: Add more threads, hide annoying errors
UKGovernmentBEIS/help-to-heat-GBIS pull request #99
Opened 2023-08-01 16:28 UTC by JoshAdamPowell

2023-08-01 16:30 UTC, CheshireSwift requested changes

2023-08-01 16:40 UTC, JoshAdamPowell commented on help_to_heat/settings.py
> +logging.getLogger("waitress.queue").setLevel(logging.ERROR)
do we have a var for what deployed environment we're in?

2023-08-03 00:36 UTC, CheshireSwift commented on help_to_heat/settings.py
> +logging.getLogger("waitress.queue").setLevel(logging.ERROR)
I suspect not currently, at least not explicitly.

2023-08-03 00:37 UTC, CheshireSwift approved these changes

2023-08-03 10:11 UTC, merged